name: chessai
description: A chess AI application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_service: ^0.4.1
  cupertino_icons: ^1.0.2
  permission_handler: ^10.4.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  screenshot: ^2.1.0
  image_picker: ^1.0.4
  camera: ^0.10.5+4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true